### ISSUE TITLE
Stacked bar charts don't work

### ISSUE THREAD

**Issue by mattliddy** [abcnews/dailygraphics#1]
Stacked bar charts don't load, even when using template data. Here's an example:

http://www.abc.net.au/dat/news/interactives/graphics/20160405-Vote-compass-test/index.html

**Comment by blakebutcher** [comment]
I've updated the stacked bar chart template to fix this, and it does fix new stacked bar charts. However deploying changes for the existing example above is not working properly. I'll look into that further...

**Comment by blakebutcher** [comment]
I'm resolving this issue but I've created another for the problem with template changes not flowing through to re-deployed graphics: #12
