### ISSUE TITLE
Slope Chart defaults to percentage

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#10]
Working in the slope chart, the figure defaults to a percentage when I need to use a numeric rating out of 10. See: http://www.abc.net.au/dat/news/interactives/graphics/20160411-VoteCompassleaders-test/index.html#mobile

**Comment by blakebutcher** [comment]
I've removed the hardcoded '%' symbols and it now uses suffixX (and prefixX and maxDecimalPlaces) to format the values
