### ISSUE TITLE
Slope Chart has strange configuration and excess blank space. 

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#11]
When new data was added in, excess blank space appeared in the chart underneath the slopes.

**Comment by blakebutcher** [comment]
Do you have a link to where I can see this happening?

**Comment by BluClare** [comment]
http://www.abc.net.au/dat/news/interactives/graphics/20160411-VoteCompassleaders-test/index.html

**Comment by BluClare** [comment]
Actually - I adjusted the numbers to percentages instead and it deleted the blank space. So when my values were numbered 3.6 instead of 36% the blank space was about the same size as the chart. this could be something to do with the minimum and maximum settings but it wasn't clear how to change those.

**Comment by blakebutcher** [comment]
My bad, I closed the wrong issue.

**Comment by blakebutcher** [comment]
@BluClare I think the excess whitespace issue is fixed. Can you please take a look to confirm, and let me know if anything is needed before this issue is closed?
