### ISSUE TITLE
Updates to the templates don't flow through to individual graphics when they are re-deployed

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/dailygraphics#12]
In #1 there was a problem with the Stacked Bar Chart template that caused the JS to break, with the following example: http://www.abc.net.au/dat/news/interactives/graphics/20160405-Vote-compass-test/index.html

The graphic template was fixed and new Stacked Bar Charts are using the updated code. However after re-deploying the example above via Chart Builder the problem remains. The template changes are not flowing through.

**Comment by blakebutcher** [comment]
So it looks like the templates are updated on newsdev, and when you deploy changes via Chart Builder that process is working fine, but the problem is that the template changes under `/dailygraphics/graphic_templates/stacked_bar_chart/` never make it over to `/graphics/20160405-Vote-compass-test/` . They are only copied over when the graphic is first created.

There are pros and cons to this, but it would potentially make sense for there to be another action in Chart Builder for refreshing the graphic templates?

@louisstow did you run into this problem? Do you know of a way of refreshing an existing graphic's templates?

**Comment by louisstow** [comment]
Yeah this was annoying. I think I ended up manually copying my changes but a way to refresh it would be great.

**Comment by blakebutcher** [comment]
OK there is now a new option in the advanced mode of Chart Builder that allows you to redeploy the templates. It will get new files from the base and template folders but it will keep the `graphic_config.py` the same because we want to keep the relationship with the content Google Sheet.
