### ISSUE TITLE
The Notes section is misaligned

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#14]

**Comment by blakebutcher** [comment]
Example bar chart with Notes section: http://www.abc.net.au/dat/news/interactives/graphics/vote-compass-bar-chart-test-/#mobile

@BluClare just to clarify, do you mean the Notes section should be aligned with Source and Credit? This seems to be a common problem across all chart types?

**Comment by BluClare** [comment]
Yes, it makes it look quite odd to have the Notes not in line with anything
else.

**Comment by blakebutcher** [comment]
OK looks like this was just an oversight when the panel styles were added. It should be fixed for new graphics.
