### ISSUE TITLE
The 'dots' on the line chart are too large on mobile.

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#16]
The dots on the line chart tend to overtake when you're looking at a chart on mobile. See example here: http://www.abc.net.au/dat/news/interactives/graphics/gt-turnbull-vs-abbott-3-months/#mobile

**Comment by blakebutcher** [comment]
![screen shot 2016-05-05 at 12 14 39 pm](https://cloud.githubusercontent.com/assets/245146/15034646/12a4dc52-12bb-11e6-802d-ae75cfda9f7c.png)

I've got a change ready to go that reduces the size of the dots and makes the lines thinner at the lower breakpoint. Is that good or does it need further tweaking?

**Comment by BluClare** [comment]
It needs further tweaking. Maybe the dots shouldn't be obvious at all.

**Comment by blakebutcher** [comment]
![screen shot 2016-05-05 at 12 30 30 pm](https://cloud.githubusercontent.com/assets/245146/15034823/3a56012a-12bd-11e6-9a5d-0efbe648bd0e.png)
How about this?

**Comment by blakebutcher** [comment]
![screen shot 2016-05-05 at 12 32 53 pm](https://cloud.githubusercontent.com/assets/245146/15034854/8be57a34-12bd-11e6-950a-28351000d772.png)
Or this?

**Comment by BluClare** [comment]
That last version is really great.

**Comment by blakebutcher** [comment]
OK new graphics should get the new styles but existing ones wont (even when you "Deploy Changes" in Chart Builder) because of issue #12
