### ISSUE TITLE
Skipping the second colour when specifying the colours of lines in a line chart.

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#19]

**Comment by blakebutcher** [comment]
Example: http://www.abc.net.au/dat/news/interactives/graphics/maylinetest/

"colors" is set to "ptylib, red, ptylab, ptygrn, grey"

The second value (red) does not appear on the graph, but the others do in correct order.

**Comment by BluClare** [comment]
@blakebutcher This same issue happens with the bar charts.

**Comment by blakebutcher** [comment]
Should be fixed for new charts.
