### ISSUE TITLE
Automatically generated Google Sheet doesn't have important label options

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#2]
There are only a few options in the automatically generated Google Sheets in the 'labels' tab. All the important options need to be listed for each new type of chart.

**Comment by blakebutcher** [comment]
Which options are you expecting to see? Are they listed somewhere?

**Comment by BluClare** [comment]
@blakebutcher There are more options listed in the documentation: https://github.com/abcnews/dailygraphics/blob/master/Documentation.md

But there is only info on line and bar charts, and not much of it appears automatically in the template sheet.

**Comment by blakebutcher** [comment]
Each graphic template has a COPY_GOOGLE_DOC_KEY for defining which Google Sheet to copy when creating a new graphic. At the moment these are all pointing to original dailygraphics sheets which we don't have access to update. So I'll need to duplicate all of these into the abcinteractives account and update the COPY_GOOGLE_DOC_KEY. Then we will be able to add more fields to appear for newly created graphics.

**Comment by blakebutcher** [comment]
I've updated the bar chart template to use an abcinteractive owned copy of the Sheet template: https://docs.google.com/spreadsheets/d/1KhWRjjUtsrI9ylf0kYZ0_G9IDQvHOup3F99nf3tko9w/edit#gid=0

In this I've added the "theme" option and restricted it to a dropdown that is populated by this sheet https://docs.google.com/spreadsheets/d/1kzcVoldQJ-WV8RcgN5ox-cwIbnhIiw7DS9eVx109RE0/edit#gid=0

I'll start working on the other options and other graphic types but I've noticed some of the other options are potentially conflicting (e.g. theme, colors, and barColors) or shouldn't be there by default (e.g. for "nocard" the value doesn't matter, just that the option is there, so I can't add it to the sheet as it is now). So I'll look into possibly updating some of these (e.g. card = true/false) so they fit better into being managed in the sheets. Also I'll think about ways the allow users to set values to their defaults but allow the overall defaults to change in the future.

**Comment by BluClare** [comment]
@blakebutcher There will also need to be a political party colour scheme option if we're to use this for the election.

**Comment by blakebutcher** [comment]
@BluClare we could add another theme with the political party colours but that would be assuming the data for the political parties are always managed in the same order. It is currently possible to use the "colors" label to define a set of comma separated colours that are used, which allows more flexibility in assigning colours to different data.

I think the best option here is to have the Google Sheet show the "theme" dropdown with an additional option of "custom". And also to have a "colors" label always show below it. Then if "custom" is selected it gets the colours from "colors", otherwise it uses the predefined colours from the selected theme.

**Comment by blakebutcher** [comment]
I've implemented what I described in my comment directly above for new line charts and bar charts.

**Comment by blakebutcher** [comment]
I've updated the line chart and bar chart Google Sheet templates to contain labels for all of the documented options, with data validation where appropriate.

To do this I had to update the "nocard" option to now be a "card" option with an on/off value (defaulting to on).

I'll resolve this issue and we can deal with further changes and the other chart types in seperate issues.
