### ISSUE TITLE
Labeling of the x and y axis does not work in line chart using the instructions in the documentation. 

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#20]
These instructions do not change the labels on the x and y axes. See: http://www.abc.net.au/dat/news/interactives/graphics/maylinetest/ 

xLabel

Default: none
Label the X axis. You may need to increase the margins if the label doesn't fit.

yLabel

Default: none
Label the Y axis.

**Comment by blakebutcher** [comment]
@BluClare I've fixed this for new Line Charts. Can you please test?

I couldn't see the same problem in the Bar Chart template. Are you sure that has the same problem?
