### ISSUE TITLE
Line charts are not showing a full date, only showing month and year. 

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#21]
Example here: http://www.abc.net.au/dat/news/interactives/graphics/maylinetest/#fluid

**Comment by blakebutcher** [comment]
I've switched line charts to use a multi-resolution time format ( https://github.com/mbostock/d3/wiki/Time-Formatting#format_multi ) which is the same as d3's default, except I've removed preceding zeros and added newlines instead of spaces.

I'll need to do the same for all the other chart types.

**Comment by blakebutcher** [comment]
I've added back in the ability to override the x axis time format using `timeFormatLarge` and `timeFormatSmall`. However these wont be multi-resolution like the default, they are limited to the one format.

**Comment by blakebutcher** [comment]
Looks like I wont need to do the same for all the other chart types, because they don't have time scales.
