### ISSUE TITLE
Implement xLabel and yLabel for bar charts

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#23]
An example here:  
http://www.abc.net.au/dat/news/interactives/graphics/maybartest/#mobile

I made sure that the spreadsheet basically matched the values layout of the line chart we've already tinkered with as a line chart test.

**Comment by blakebutcher** [comment]
Relates to #20 & #19

**Comment by blakebutcher** [comment]
The colour problem should be fixed in #19.

The xLabel and yLabel don't appear to have been implemented for bar charts yet. I'll update this issue to look at that specifically.

**Comment by blakebutcher** [comment]
The bar chart designs in Trello do not have X or Y axis labels: https://trello.com/c/JbqWq0sY/19-bar-chart

@BluClare if you'd like to pursue this one further can you please discuss with Ben and get him to provide updated designs?
