### ISSUE TITLE
How do I set up a date and time column in a line chart?

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#24]
I tried to do use a time/date series that looks like this: 

time    One Two
2016-05-03-00:00    7   2
2016-05-03-01:00    6   1
2016-05-03-02:00    6   1

I couldn't work out how to match it back up in the values spreadsheet: http://www.abc.net.au/dat/news/interactives/graphics/trendsmaylinetest/

**Comment by blakebutcher** [comment]
Fixed. The `parseDateFormat` needed to be `%Y-%m-%d-%H:%M`
