### ISSUE TITLE
Add option of showing the labels in a legend instead of on the right of the graph

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/dailygraphics#26]

**Comment by blakebutcher** [comment]
Looks like this was already implemented in the original dailygraphics project but removed in our fork.

@louisstow do you know the back story for this? Was it replaced with the labels to the right? Is it because the legend relies on colour to distinguish between data sets and is therefore not accessible?

**Comment by BenSpraggon** [comment]
@blakebutcher Yes to both of your questions to @louisstow. Labeling elements directly is always a better option. However, on small devices we may start to eat into too much plotting space so ideally if a label is too long (don't really know what too long is yet) and it can't be broken into multiple lines then we'd revert back to a legend to ensure the plot is legible. If we stick to the provided colour schemes and line styles it should still be mostly accessible but it won't be completely compliant.

**Comment by blakebutcher** [comment]
I'll resolve this issue and we can make a new one if we notice labels using up too much plotting space on mobile.
