### ISSUE TITLE
Pie charts: do we want?

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/dailygraphics#39]
Looks like there was a start on making pie charts, but there is no design for them in Trello.

Do we actually want to be able to create pie charts or are other chart types more effective in presenting the same data?

**Comment by BenSpraggon** [comment]
Generally other charts are more effective unless you are only looking at two categories. We will want to work on pie charts eventually but it's not high priority at the moment.

**Comment by blakebutcher** [comment]
I found that pie charts were actually more advanced than I first thought. I've added them to the chart builder interface so they can be experimented with. Any further development on them can be done in new issues.
