### ISSUE TITLE
Line chart with new data did not work until I added these values to the label tab

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#4]
See sheet:
https://docs.google.com/spreadsheets/d/1-9mKBm5BZKns9D3MdOdDZWnMoZ1WWVAGMlpWyDpYsGI/edit#gid=0

interpolate linear
marginRight 180
xLabel       Week
marginBottom    20
yLabel  Percentage of Vote Compass responses
theme   multicolor
colors  
timeFormatSmall %y
minValue    0
maxValue    60
ticksX  6

**Comment by BluClare** [comment]
Could not work out how to fix this one.... http://www.abc.net.au/dat/news/interactives/graphics/20160411-Votecompassleadersline-test/index.html 
https://docs.google.com/spreadsheets/d/1auWUjv9r6MkKyuDraK8ysFTTwC75x4gbfIN9-CS6MNQ/edit#gid=0

**Comment by blakebutcher** [comment]
For http://www.abc.net.au/dat/news/interactives/graphics/20160411-Votecompassleadersline-test/index.html there seemed to be 2 problems:
1. The dates in the spreadsheet were set to a "Date" number format. I changed this to "Plain Text" to make it consistent with the example
2. The `parseDateFormat` value was incorrect. I updated it to `%-m/%-d/%Y`

It may be possible that there is a `parseDateFormat` that is compatible with the "Date" number format but I'd need to investigate that further.

**Comment by BluClare** [comment]
I've tested this again today, and the chart won't work properly with new data pasted in and if I don't change anything in the 'values' tab

**Comment by BluClare** [comment]
On the mobile configuration, the dates just appear as "16" which means 2016 but would be incomprehensible to a reader. See example here: http://www.abc.net.au/dat/news/interactives/graphics/gt-turnbull-vs-abbott-3-months/#mobile

**Comment by blakebutcher** [comment]
@BluClare Can you please make a seperate issue for the 2016/16 problem?

**Comment by BluClare** [comment]
I've made it issue #18

**Comment by blakebutcher** [comment]
I think this has all been sorted in #2
