### ISSUE TITLE
Charts not redeploying

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#40]
![image](https://cloud.githubusercontent.com/assets/18301380/15413957/fa11e79c-1e78-11e6-9a3d-0ceadca4e037.png)

See: http://www.abc.net.au/dat/news/interactives/graphics/2016-election-campaign-ads-cumulative-total/

**Comment by blakebutcher** [comment]
Not sure what the cause of this was but redeploying the template seems to have fixed it. Let me know if it happens again.

**Comment by blakebutcher** [comment]
Not sure what the cause of this was but redeploying the template seems to have fixed it. Let me know if it happens again.

**Comment by blakebutcher** [comment]
Not sure what the cause of this was but redeploying the template seems to have fixed it. Let me know if it happens again.
