### ISSUE TITLE
Line chart x-axis date labels not displaying correctly

### ISSUE THREAD

**Issue by BenSpraggon** [abcnews/dailygraphics#42]
Looks like:
[
![bad](https://cloud.githubusercontent.com/assets/19443071/15414702/7a588d46-1e80-11e6-9a1e-5b15f6b6ab06.png)
](url)

Should be:
![better](https://cloud.githubusercontent.com/assets/19443071/15414677/4ef5fd82-1e80-11e6-80a1-9a70149d6237.png)

**Comment by blakebutcher** [comment]
@BenSpraggon the default date format is a [multi resolution time format](https://github.com/d3/d3/wiki/Time-Formatting#format_multi) but this can be overridden in the Google Sheet using the [timeFormatLarge](https://github.com/abcnews/dailygraphics/blob/master/Documentation.md#timeformatlarge) and [timeFormatSmall](https://github.com/abcnews/dailygraphics/blob/master/Documentation.md#timeformatsmall) options.

**Comment by blakebutcher** [comment]
@BenSpraggon would you be happy for this issue to be resolved, or should I look into using a single date format (perhaps dynamically based on the axis scale) as the default?
