### ISSUE TITLE
State grid map non responsive to new dataset

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#5]
https://docs.google.com/spreadsheets/d/198QdyOffMbtXyByVzEz-YaOrqp5w8aM30fsLEq-r5_U/edit#gid=1281681967

I tried to input Australian electorates instead of American states. This did not work in the visualisation. Very odd outcomes. However the default data works.

**Comment by BluClare** [comment]
This may need a lot of work to get it up to scratch. This may be a low priority.

**Comment by blakebutcher** [comment]
This state grid map is specific to USA states. I've updated the label in Chart Builder to make this clearer. If we want something similar for other countries we'll need to make them as new graphic types.
