### ISSUE TITLE
In Production preview area, 'Refresh Content' button is ineffective

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#54]
'Refresh content' - doesn't work in either the staging preview area nor the production preview area. It only works if you hit the publish button - which undermines the whole point of having two areas. You need to publish before you can see changes.

**Comment by blakebutcher** [comment]
It works in the staging preview area for me.

With the separation of the deployment process those "Refresh content" links on the preview areas now really mean "Refresh content on staging". So from both the staging and production preview areas clicking it will only update the staging version.

I'll need to do some work to clearly distinguish the staging and production preview areas, and provide different links for each environment, and easy navigation between them.

In the meantime using the main Chart Builder interface is the only option for deploying changes into production.

**Comment by blakebutcher** [comment]
New graphics or any that have their templates rebuilt (via the advanced dropdowns) will now get environment specific buttons and labels.
