### ISSUE TITLE
Invert bar overlay text when lighter bar colour used

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/dailygraphics#55]
These two chart types have values over the bars:
http://newsdev3.aus.aunty.abc.net.au/tools/chart-builder/graphics/blake-stacked-column-chart/build/
http://newsdev3.aus.aunty.abc.net.au/tools/chart-builder/graphics/blake-stacked-bar-chart/build/

At the moment the bar text colour is always white and the bar colours are darkened to make them accessible.

Instead we could check if bar colour is dark or light. If the bar colour is lighter than the midpoint it would use black text over an accessibly lightened bar colour. And if the bar colour is darker it would use the white text over an accessibly darkened bar colour. (like this http://d3bo5ucoqkgs8h.cloudfront.net/IGiIY/1/ )

@BenSpraggon what do you think?

**Comment by BenSpraggon** [comment]
My preference is not to use stacked bar or column charts at all except when there are only 2 variables. I'd also prefer for there not to be any text over the chart elements. Until we come up with a solid alternative to stacked bar and column charts I guess this is a good interim solution.

**Comment by blakebutcher** [comment]
Thanks @BenSpraggon I'll make the change to the colours.

RE: only using 2 variables in stacked charts... is that something you think should be restricted (maybe using sheet restrictions or in the code)?
and/or should we put something in the documentation?

**Comment by blakebutcher** [comment]
I've changed the colours.

@BenSpraggon if you would like the number of vars restricted or documented can you please create another issue?
