### ISSUE TITLE
New graphic type: Sparklines

### ISSUE THREAD

**Issue by blakebutcher** [abcnews/dailygraphics#57]
https://trello.com/c/HDsQVuuk/23-sparklines-small-multiples
https://trello.com/c/2qtYrsIZ/24-sparklines-inline

**Comment by phocks** [comment]
Hi everyone. Sparklines are now live! They show the data when you hover over them. http://newsdev3.aus.aunty.abc.net.au/tools/chart-builder/graphics/test-sparkline-josh/build/ Hopefully in the future we will be able to create some inline sparklines that we can embed within paragraph text like in this long essay on sparklines https://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR

I still need to edit documentation for them though.

![snip20170628_3](https://user-images.githubusercontent.com/437566/27668370-10f01af8-5cc4-11e7-83b2-3540580b93ee.png)

**Comment by drzax** [comment]
I'll leave this open until you've merged the documentation, but nice work. Close when docs are merged.

**Comment by phocks** [comment]
Thanks, documentation is now merged.
