### ISSUE TITLE
Very Basic Chart does not load, even with template dataset

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#6]
See:
http://www.abc.net.au/dat/news/interactives/graphics/20160406-verybasicnewgraphic-test/index.html

**Comment by blakebutcher** [comment]
All the graphs seem to have a fallback to a static image (but that `fallback.png` doesn't exist for any of them). I suspect the "Very basic chart" is where the image is intended to be presented to the audience and not just as a fallback.

So I think what we need here is a way of defining the `fallback.png` for all graphic types (and possibly a way of automating the creation of the `fallback.png` for some of them?)

@louisstow does that sound right to you?

**Comment by louisstow** [comment]
I couldn't find out how fallback.png was supposed to be generated (or if it was supposed to be manual) so I removed it from most of the common templates.

**Comment by blakebutcher** [comment]
Relates to #34

**Comment by blakebutcher** [comment]
We will be looking at automating the creation of the fallback.png, so there is no actual desire for editors to use the "Very Basic Chart" type. It is now hidden away in the advanced mode of Chart Builder.
