### ISSUE TITLE
Documentation needs more info on how to assign colours to the charts

### ISSUE THREAD

**Issue by BluClare** [abcnews/dailygraphics#7]

**Comment by BluClare** [comment]
I've found more information that was shared on the Trello Page:

From Ben Spraggon: 

"There are several colour scheme available for each chart type. Colour is only ever used as an adjunct-- elements are always labeled. All of these colour schemes are sensitive to the majority of colour blind users. The default colour scheme is Single Colour. Colours in each scheme are different depending on if the chart is line or dot based; or if the chart is block based.

Available colour schemes for each chart type:

Line chart
- Single Colour
- Monochrome
- Highlighted
- Multi-Colour
- Political Colours

To aid with differentiation some colours are used in conjunction with different line styles

Sparklines
- Single Colour

Column chart
- Single Colour
- Monochrome
- Highlighted
- Political Colours

Bar chart
- Single Colour
- Monochrome
- Highlighted
- Political Colours

Grouped Bar chart
- Single Colour
- Monochrome
- Highlighted

Small multiple Grouped Bar chart
- Single Colour
- Monochrome
- Highlighted
- Political Colours

Small multiple dot chart
- Single Colour
- Monochrome
- Highlighted
- Political Colours

Slope Chart
- Single Colour
- Monochrome
- Highlighted
- Multi-Colour
- Political Colours"

**Comment by BluClare** [comment]
I went to test this in 'state grid', but am not sure of the useable colour option for 'state grid' https://docs.google.com/spreadsheets/d/198QdyOffMbtXyByVzEz-YaOrqp5w8aM30fsLEq-r5_U/edit#gid=0

**Comment by blakebutcher** [comment]
The chart types I've looked at so far (line chart, bar chart, grouped bar chart) now have "theme" as a dropdown (with the themes applicable to that chart type) and the "color" label ready to populate (when used with "custom" theme). I've also updated the documentation to cover this.

I'll do the same for the other chart types.

**Comment by blakebutcher** [comment]
`theme` and `color` are now default labels in the following chart types:
- line chart
- slopegraph
- column chart
- stacked column chart
- dot chart
- bar chart
- grouped bar chart
- stacked bar chart
- pie chart
- block histogram
